# Generated by Django 4.0.1 on 2022-02-19 04:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupType',
        ),
        migrations.RenameField(
            model_name='friends',
            old_name='creaded_on',
            new_name='created_on',
        ),
        migrations.AlterUniqueTogether(
            name='groups',
            unique_together={('group_admin', 'group_name')},
        ),
        migrations.RemoveField(
            model_name='groups',
            name='group_type',
        ),
    ]
