# Generated by Django 4.0.1 on 2022-02-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_groups_group_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_details',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
