# Generated by Django 4.0.1 on 2022-02-19 03:38

import calculation.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_period', models.DateField(auto_now_add=True)),
                ('end_period', models.DateField(blank=True, null=True)),
                ('per_head', models.CharField(blank=True, max_length=255, null=True)),
                ('total_expenses', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cal_group_id', to='group.groups')),
            ],
        ),
        migrations.CreateModel(
            name='TotalExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calculation_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Total_cal_period', to='calculation.calculationperiod')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_id_total', to='group.groups')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calculation_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Personal_cal_period', to='calculation.calculationperiod')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_id_personal', to='group.groups')),
                ('spender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spender_id_personal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('calculation_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_cal_period', to='calculation.calculationperiod')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_id_final', to='group.groups')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bill', models.ImageField(blank=True, null=True, upload_to=calculation.models.upload_bill_image_path)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('exp_note', models.CharField(blank=True, max_length=255)),
                ('calculation_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cal_period', to='calculation.calculationperiod')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_group_id', to='group.groups')),
                ('spender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
